name: ci

on:
  push:
    branches:
      - 'main'
      - 'fix-directory-transfer-error'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          PYTHON_VERSION: ${{ matrix.python }}
        with:
          name: nsglobusautobuilds/jupyterlab-testing
          snapshot: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: PYTHON_VERSION
