# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -r test-requirements.txt
      - name: Test with pytest
        run: |
          pytest --cov globus_jupyterlab --cov-report term-missing
      - name: Test Docs
        if: ${{ matrix.python-version == '3.10' && matrix.os == 'ubuntu-latest' }}
        run: |
          pip install -r docs/requirements.txt
          cd docs
          make html
