name: ci

on:
  push:
    branches:
      - "eks-resource-server-testing"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          PYTHON_VERSION: ${{ matrix.python }}
        with:
          name: nsglobusautobuilds/jupyterhub-service-testing
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: PYTHON_VERSION
          tags: "latest"
          workdir: "globus_jupyterlab/tests/integration/hub-service"
